---@type NvPluginSpec
return {
  "danielfalk/smart-open.nvim",
  branch = "0.2.x",
  config = function()
    require("telescope").load_extension "smart_open"
  end,
  dependencies = { "kkharji/sqlite.lua" },
  keys = {
    {
      "<leader><leader>",
      function()
        require("telescope").extensions.smart_open.smart_open {
          cwd_only = true,
          filename_first = true,
          result_limit = 20,
          ignore_patterns = {
            -- Custom
            "*.jj/*",

            -- Defaults
            "*.git/*",
            "*build/*",
            "*debug/*",
            "*.pdf",
            "*.ico",
            "*.class",
            "*~",
            "~:",
            "*.jar",
            "*.node",
            "*.lock",
            "*.gz",
            "*.zip",
            "*.7z",
            "*.rar",
            "*.lzma",
            "*.bz2",
            "*.rlib",
            "*.rmeta",
            "*.DS_Store",
            "*.cur",
            "*.png",
            "*.jpeg",
            "*.jpg",
            "*.gif",
            "*.bmp",
            "*.avif",
            "*.heif",
            "*.jxl",
            "*.tif",
            "*.tiff",
            "*.ttf",
            "*.otf",
            "*.woff*",
            "*.sfd",
            "*.pcf",
            "*.ico",
            "*.svg",
            "*.ser",
            "*.wasm",
            "*.pack",
            "*.pyc",
            "*.apk",
            "*.bin",
            "*.dll",
            "*.pdb",
            "*.db",
            "*.so",
            "*.spl",
            "*.min.js",
            "*.min.gzip.js",
            "*.so",
            "*.doc",
            "*.swp",
            "*.bak",
            "*.ctags",
            "*.doc",
            "*.ppt",
            "*.xls",
            "*.pdf",
          },
        }
      end,
      desc = "Telescope Smart Open",
    },
  },
}
